#!/bin/sh
# Install LuCI language packs based on system timezone.

ZONENAME=$(uci -q get system.@system[0].zonename)
case "$ZONENAME" in
    Asia/Shanghai|Asia/Kuala_Lumpur|Asia/Singapore)
        apk add luci-i18n-base-zh-cn luci-i18n-package-manager-zh-cn luci-i18n-usteer-zh-cn
        ;;
esac

exit 0
