#!/bin/sh

apk update

# apk add luci

# Install LuCI language packs based on system timezone.
ZONENAME=$(uci -q get system.@system[0].zonename)
case "$ZONENAME" in
    Asia/Shanghai)
        apk add luci-i18n-base-zh-cn luci-i18n-package-manager-zh-cn luci-i18n-firewall-zh-cn
        ;;
esac

exit 0
